name: Build project
on:
  push:
    branches:
      - main
    paths-ignore:
      - "snap/**"
  pull_request:

jobs:
  build-linux:
    runs-on: ubuntu-20.04
    container: quay.io/centos/centos:stream8
    steps:
      - name: Update and install packages
        run: |
          dnf -y config-manager --set-enabled powertools
          dnf -y install epel-release epel-next-release
          dnf -y update
          dnf -y install cmake make nasm qt5-qtwebsockets-devel hidapi-devel zlib-devel libpng-devel SDL2-devel wget zip git
          ln -s /usr/bin/qmake-qt5 /usr/bin/qmake
      - name: Install SDL2_net
        run: |
          wget https://www.libsdl.org/projects/SDL_net/release/SDL2_net-2.0.1.tar.gz
          tar xf SDL2_net-2.0.1.tar.gz
          cd SDL2_net-2.0.1
          ./configure --prefix=/usr
          make -j4
          make install
          cd ..
      - uses: actions/checkout@v2
      - name: Get short SHA
        id: slug
        run: echo "::set-output name=sha7::$(git rev-parse --short HEAD)"
      - name: Run build script
        run: |
          export M64P_AUTOUPDATE=1
          bash ./build.sh
      - name: Upload zip
        uses: actions/upload-artifact@v2
        with:
          name: m64p-linux64-${{ steps.slug.outputs.sha7 }}.zip
          path: m64p-*.zip
  build-windows:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v2
      - name: Get short SHA
        id: slug
        run: echo "::set-output name=sha7::$(git rev-parse --short HEAD)"
      - uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >-
            make
            mingw-w64-x86_64-cmake
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-hidapi
            mingw-w64-x86_64-freetype
            mingw-w64-x86_64-libpng
            mingw-w64-x86_64-SDL2
            mingw-w64-x86_64-SDL2_net
            mingw-w64-x86_64-jasper
            mingw-w64-x86_64-qt5
            mingw-w64-x86_64-python3-pip
            mingw-w64-x86_64-python3-pyopenssl
            mingw-w64-x86_64-nasm
            git
            zip
      - name: Run build script
        run: msys2 -c 'export M64P_AUTOUPDATE=1; ./build.sh'
        env:
          HOST_CPU: x86_64
          MSBUILD_PATH: "/c/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/MSBuild/Current/Bin/"
      - name: Upload zip
        uses: actions/upload-artifact@v2
        with:
          name: m64p-win64-${{ steps.slug.outputs.sha7 }}.zip
          path: m64p-*.zip
#  build-mac:
#    runs-on: macos-10.15
#    steps:
#      - uses: actions/checkout@v2
#      - name: Get short SHA
#        id: slug
#        run: echo "::set-output name=sha7::$(git rev-parse --short HEAD)"
#      - name: brew update
#        run: |
#          brew update
#          brew install hidapi sdl2_net sdl2 qt@5
#      - name: Run build script
#        run: |
#          export qt_version=$(ls /usr/local/Cellar/qt@5)
#          sudo ln -s /usr/local/Cellar/qt@5/$qt_version/plugins /usr/local/plugins
#          sudo ln -s /usr/local/Cellar/qt@5/$qt_version/mkspecs /usr/local/mkspecs
#          sudo ln -s /usr/local/Cellar/qt@5/$qt_version/bin/qmake /usr/local/bin/qmake
#          export PATH=$PATH:/usr/local/Cellar/qt@5/$qt_version/bin
#          sudo sh ./build.sh
#      - name: Upload dmg
#        uses: actions/upload-artifact@v2
#        with:
#          name: m64p-osx-${{ steps.slug.outputs.sha7 }}.dmg
#          path: mupen64plus/m64p-*.dmg
