name: Upload snap

on:
  release:
    types: [published]
  workflow_dispatch:

env:
  SNAPCRAFT_BUILD_ENVIRONMENT: host
  PYTHON_VERSION: "3.9"

jobs:
  build-snap:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Get snapcraft login
        run: echo "$SNAPCRAFT_LOGIN" > $GITHUB_WORKSPACE/SNAPCRAFT_LOGIN.txt
        env:
          SNAPCRAFT_LOGIN: ${{ secrets.SNAPCRAFT_LOGIN }}

      - name: Install snapcraft and login
        run: |
          sudo snap install snapcraft --classic
          snapcraft login --with $GITHUB_WORKSPACE/SNAPCRAFT_LOGIN.txt

      - name: Run snapcraft
        run: |
          pip install requests
          export M64P_VERSION=$(python3 scripts/get_release_version.py)
          export M64P_LINUX_URL=$(python3 scripts/get_linux_asset.py $M64P_VERSION)
          sed -i "s~M64PVERSION~$M64P_VERSION~g" snap/snapcraft.yaml
          sed -i "s~M64PURL~$M64P_LINUX_URL~g" snap/snapcraft.yaml
          snapcraft
          snapcraft upload --release=stable *.snap
