name: Upload toolbox container

on:
  release:
  workflow_dispatch:

env:
  REGISTRY_USER: loganmc10
  IMAGE_REGISTRY: quay.io
  REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
  PYTHON_VERSION: "3.9"

jobs:
  build-toolbox:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Log in to Quay.io
        uses: redhat-actions/podman-login@v1
        with:
          username: ${{ env.REGISTRY_USER }}
          password: ${{ env.REGISTRY_PASSWORD }}
          registry: ${{ env.IMAGE_REGISTRY }}

      - name: Run podman
        run: |
          pip install requests
          export M64P_VERSION=$(python3 ../scripts/get_release_version.py)
          export M64P_LINUX_URL=$(python3 ../scripts/get_linux_asset.py $M64P_VERSION)
          sed -i "s~M64PURL~$M64P_LINUX_URL~g" Containerfile
          podman build . --tag quay.io/loganmc10/m64p:latest --tag quay.io/loganmc10/m64p:$M64P_VERSION
          podman push quay.io/loganmc10/m64p:latest
          podman push quay.io/loganmc10/m64p:$M64P_VERSION
        working-directory: toolbox
